config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :poker_hands
  root to: 'poker_hands#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poker_hand.rb
class PokerHand < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/poker_hands_controller.rb
require './app/services/poker_hand_service'

class PokerHandsController < ApplicationController
  before_action :set_poker_hand, only: %i[show edit update destroy]

  # GET /poker_hands or /poker_hands.json
  def index
    @poker_hands = PokerHand.all
  end

  # GET /poker_hands/1 or /poker_hands/1.json
  def show; end

  # GET /poker_hands/new
  def new
    @poker_hand = PokerHand.new
  end

  # GET /poker_hands/1/edit
  def edit; end

  # POST /poker_hands or /poker_hands.json
  def create
    user_poker_hand = params[:poker_hand][:cards].split(' ')
    poker_hand_service = PokerHandService.new(user_poker_hand)
    ranked_hand = poker_hand_service.rank_hand
    user_poker_hand = user_poker_hand.join(' ')

    @poker_hand = PokerHand.new({
                                  cards: user_poker_hand,
                                  ranking_type: ranked_hand.ranking_type,
                                  rank_no: ranked_hand.rank_no,
                                  is_ranking_type: ranked_hand.is_ranking_type
                                })

    respond_to do |format|
      if @poker_hand.save
        format.html { redirect_to @poker_hand, notice: 'Poker hand was successfully created.' }
        format.json { render :show, status: :created, location: @poker_hand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @poker_hand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poker_hands/1 or /poker_hands/1.json
  def update
    respond_to do |format|
      if @poker_hand.update(poker_hand_params)
        format.html { redirect_to @poker_hand, notice: 'Poker hand was successfully updated.' }
        format.json { render :show, status: :ok, location: @poker_hand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @poker_hand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poker_hands/1 or /poker_hands/1.json
  def destroy
    @poker_hand.destroy
    respond_to do |format|
      format.html { redirect_to poker_hands_url, notice: 'Poker hand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_poker_hand
    @poker_hand = PokerHand.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def poker_hand_params
    params.require(:poker_hand).permit(:cards, :ranking_type, :rank_no, :is_ranking_type)
  end
end

app/helpers/poker_hands_helper.rb
module PokerHandsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokerHandChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/poker_hands/_form.html.erb
<%= form_with(model: poker_hand) do |form| %>
  <% if poker_hand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poker_hand.errors.count, "error") %> prohibited this poker_hand from being saved:</h2>

      <ul>
        <% poker_hand.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cards %>
    <%= form.text_field :cards %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/poker_hands/edit.html.erb
<h1>Editing Poker Hand</h1>

<%= render 'form', poker_hand: @poker_hand %>

<%= link_to 'Show', @poker_hand %> |
<%= link_to 'Back', poker_hands_path %>

app/views/poker_hands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Poker Hands</h1>

<table>
  <thead>
    <tr>
      <th>Cards</th>
      <th>Ranking type</th>
      <th>Rank no</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @poker_hands.each do |poker_hand| %>
      <tr>
        <td><%= poker_hand.cards %></td>
        <td><%= poker_hand.ranking_type %></td>
        <td><%= poker_hand.rank_no %></td>
        <td><%= link_to 'Show', poker_hand %></td>
        <td><%= link_to 'Destroy', poker_hand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poker Hand', new_poker_hand_path %>

app/views/poker_hands/new.html.erb
<h1>New Poker Hand</h1>

<%= render 'form', poker_hand: @poker_hand %>

<%= link_to 'Back', poker_hands_path %>

app/views/poker_hands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cards:</strong>
  <%= @poker_hand.cards %>
</p>

<p>
  <strong>Ranking type:</strong>
  <%= @poker_hand.ranking_type %>
</p>

<p>
  <strong>Rank no:</strong>
  <%= @poker_hand.rank_no %>
</p>

<%= link_to 'Back', poker_hands_path %>